site_name: Melonland

pages:
- Home: index.md
- HD Guide:
    - Quick Start: guide/quickstart.md
    - Example Snippets: guide/snippets.md
- HD Features:
    - Preamble Options: features/preamble.md
    - Finding Elements: features/finding-elements.md
- HD FAQ:
    - FAQ: faq.md
    - Install Webdriver: faq/install-webdriver.md
    - Contributing: faq/contributing.md
    - Regex: faq/regex.md

site_dir: dist/docs

theme: readable
theme: mkdocs

markdown_extensions:
    - toc:
        permalink: ÔÉÅ